### ISSUE TITLE
Issue installing gotests on vscode

### ISSUE THREAD

**Issue by josedh** [cweill/gotests#39]
Hello everyone. I have an issue trying to install gotests on my mac machine:
Steps:
Click the 'Analysis tool missing' option in the bottom right corner of vscode.
Installation begings:

Installing 1 tools
  gotests

Installing gotests FAILED

1 tools failed to install.

gotests:
Error: Command failed: /usr/local/go/bin/go get -u -v github.com/cweill/gotests/...
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
github.com/cweill/gotests/internal/render/bindata
golang.org/x/tools/imports
github.com/cweill/gotests/internal/render
github.com/cweill/gotests/internal/output
github.com/cweill/gotests
github.com/cweill/gotests/gotests/process
github.com/cweill/gotests/gotests
# github.com/cweill/gotests/gotests
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x3ea0ccbb070c pc=0xf47b]

runtime stack:
runtime.throw(0x2c4900, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3a60a0)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3a60a0, 0x1, 0xf, 0xc820000180)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc82048be58)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3a60a0, 0x1, 0x1000000000f, 0xf11f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3a7a00, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3a7a00, 0x55b440)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x4022c0, 0xc80000000f, 0x55b440)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820025500)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc82003ca38 sp=0xc82003ca30
runtime.mallocgc(0xe0, 0x2641c0, 0x0, 0x9d3)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc82003cb10 sp=0xc82003ca38
runtime.newobject(0x2641c0, 0xc820c711c0)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc82003cb38 sp=0xc82003cb10
cmd/link/internal/ld.readsym(0xc820082240, 0xc820c711c0, 0xc820936d70, 0x6, 0xc820d77680, 0x2f)
	/usr/local/go/src/cmd/link/internal/ld/objfile.go:281 +0x13ba fp=0xc82003cf80 sp=0xc82003cb38
cmd/link/internal/ld.ldobjfile(0xc820082240, 0xc820c711c0, 0xc820936d70, 0x6, 0x73025, 0xc820d77680, 0x2f)
	/usr/local/go/src/cmd/link/internal/ld/objfile.go:147 +0xa62 fp=0xc82003d190 sp=0xc82003cf80
cmd/link/internal/ld.ldobj(0xc820c711c0, 0xc820936d70, 0x6, 0x7304e, 0xc820d77680, 0x2f, 0xc82077df20, 0x27, 0x1, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:1351 +0x1569 fp=0xc82003d400 sp=0xc82003d190
cmd/link/internal/ld.objfile(0xc820c95dc0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:847 +0x10d9 fp=0xc82003d710 sp=0xc82003d400
cmd/link/internal/ld.loadlib()
	/usr/local/go/src/cmd/link/internal/ld/lib.go:513 +0x5ce fp=0xc82003d9f0 sp=0xc82003d710
cmd/link/internal/ld.Ldmain()
	/usr/local/go/src/cmd/link/internal/ld/pobj.go:214 +0x1cd3 fp=0xc82003de70 sp=0xc82003d9f0
cmd/link/internal/amd64.Main()
	/usr/local/go/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc82003de78 sp=0xc82003de70
main.main()
	/usr/local/go/src/cmd/link/main.go:27 +0x36f fp=0xc82003df50 sp=0xc82003de78
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc82003dfa0 sp=0xc82003df50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003dfa8 sp=0xc82003dfa0
github.com/cweill/gotests (download)
Fetching https://golang.org/x/tools/imports?go-get=1
Parsing meta tags from https://golang.org/x/tools/imports?go-get=1 (status code 200)
get "golang.org/x/tools/imports": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/imports?go-get=1
get "golang.org/x/tools/imports": verifying non-authoritative meta tag
Fetching https://golang.org/x/tools?go-get=1
Parsing meta tags from https://golang.org/x/tools?go-get=1 (status code 200)
golang.org/x/tools (download)
Fetching https://golang.org/x/tools/go/ast/astutil?go-get=1
Parsing meta tags from https://golang.org/x/tools/go/ast/astutil?go-get=1 (status code 200)
get "golang.org/x/tools/go/ast/astutil": found meta tag main.metaImport{Prefix:"golang.org/x/tools", VCS:"git", RepoRoot:"https://go.googlesource.com/tools"} at https://golang.org/x/tools/go/ast/astutil?go-get=1
get "golang.org/x/tools/go/ast/astutil": verifying non-authoritative meta tag
github.com/cweill/gotests/internal/render/bindata
golang.org/x/tools/imports
github.com/cweill/gotests/internal/render
github.com/cweill/gotests/internal/output
github.com/cweill/gotests
github.com/cweill/gotests/gotests/process
github.com/cweill/gotests/gotests
# github.com/cweill/gotests/gotests
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x3ea0ccbb070c pc=0xf47b]

runtime stack:
runtime.throw(0x2c4900, 0x2a)
	/usr/local/go/src/runtime/panic.go:547 +0x90
runtime.sigpanic()
	/usr/local/go/src/runtime/sigpanic_unix.go:12 +0x5a
runtime.unlock(0x3a60a0)
	/usr/local/go/src/runtime/lock_sema.go:107 +0x14b
runtime.(*mheap).alloc_m(0x3a60a0, 0x1, 0xf, 0xc820000180)
	/usr/local/go/src/runtime/mheap.go:492 +0x314
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc82048be58)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0x3a60a0, 0x1, 0x1000000000f, 0xf11f)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0x3a7a00, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0x3a7a00, 0x55b440)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0x4022c0, 0xc80000000f, 0x55b440)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc820025500)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1051

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc82003ca38 sp=0xc82003ca30
runtime.mallocgc(0xe0, 0x2641c0, 0x0, 0x9d3)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc82003cb10 sp=0xc82003ca38
runtime.newobject(0x2641c0, 0xc820c711c0)
	/usr/local/go/src/runtime/malloc.go:781 +0x42 fp=0xc82003cb38 sp=0xc82003cb10
cmd/link/internal/ld.readsym(0xc820082240, 0xc820c711c0, 0xc820936d70, 0x6, 0xc820d77680, 0x2f)
	/usr/local/go/src/cmd/link/internal/ld/objfile.go:281 +0x13ba fp=0xc82003cf80 sp=0xc82003cb38
cmd/link/internal/ld.ldobjfile(0xc820082240, 0xc820c711c0, 0xc820936d70, 0x6, 0x73025, 0xc820d77680, 0x2f)
	/usr/local/go/src/cmd/link/internal/ld/objfile.go:147 +0xa62 fp=0xc82003d190 sp=0xc82003cf80
cmd/link/internal/ld.ldobj(0xc820c711c0, 0xc820936d70, 0x6, 0x7304e, 0xc820d77680, 0x2f, 0xc82077df20, 0x27, 0x1, 0x0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:1351 +0x1569 fp=0xc82003d400 sp=0xc82003d190
cmd/link/internal/ld.objfile(0xc820c95dc0)
	/usr/local/go/src/cmd/link/internal/ld/lib.go:847 +0x10d9 fp=0xc82003d710 sp=0xc82003d400
cmd/link/internal/ld.loadlib()
	/usr/local/go/src/cmd/link/internal/ld/lib.go:513 +0x5ce fp=0xc82003d9f0 sp=0xc82003d710
cmd/link/internal/ld.Ldmain()
	/usr/local/go/src/cmd/link/internal/ld/pobj.go:214 +0x1cd3 fp=0xc82003de70 sp=0xc82003d9f0
cmd/link/internal/amd64.Main()
	/usr/local/go/src/cmd/link/internal/amd64/obj.go:44 +0x19 fp=0xc82003de78 sp=0xc82003de70
main.main()
	/usr/local/go/src/cmd/link/main.go:27 +0x36f fp=0xc82003df50 sp=0xc82003de78
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc82003dfa0 sp=0xc82003df50
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc82003dfa8 sp=0xc82003dfa0

**Comment by jdelaohernandez** [comment]
I hope this is the correct place to put this in. If not, please let me know. Thanks.

**Comment by cweill** [comment]
Did you figure out the issue? Since this was installed with VSCode, try posting to https://github.com/Microsoft/vscode-go. 

Maybe try deleting and reinstalling `golang.org/x/tools/imports` with `go get`?

**Comment by cweill** [comment]
Closing due to lack of activity.
