### ISSUE TITLE
panic: interface conversion: ast.Expr is nil, not *ast.StructType

### ISSUE THREAD

**Issue by costela** [cweill/gotests#49]
The following minimal code (which correctly builds) reliably leads to a panic:
```go
package main

import "net/url"

type something url.URL

func (smtg *something) UnmarshalJSON(bytes []byte) error {
	x := &url.URL{}
	smtg = (*something)(x)
	return nil
}

func main() {}

```

Generates the following panic:
```
$ gotests -w -all gotestspanic.go
panic: interface conversion: ast.Expr is nil, not *ast.StructType

goroutine 20 [running]:
github.com/cweill/gotests/internal/goparser.parseReceiver(0xc420073fb0, 0xc420231290, 0xc4202312c0, 0x8c59c0)
	/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:220 +0x430
github.com/cweill/gotests/internal/goparser.parseFunc(0xc4202300f0, 0xc420231290, 0xc4202312c0, 0x1)
	/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:173 +0x9d
github.com/cweill/gotests/internal/goparser.(*Parser).parseFunctions(0xc42006bee8, 0xc42000eac0, 0xc4201ba500, 0xc42000c1b8, 0x1, 0x1, 0x29a, 0x1, 0x1)
	/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:105 +0x108
github.com/cweill/gotests/internal/goparser.(*Parser).Parse(0xc42006bee8, 0x7ffd49b286e2, 0x30, 0xc42008ca90, 0x1, 0x1, 0x20, 0x18, 0x6b6a00)
	/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:58 +0x2da
github.com/cweill/gotests.generateTest(0x7ffd49b286e2, 0x30, 0xc42008ca90, 0x1, 0x1, 0xc42008a900, 0x0, 0xc4200297a0, 0x5141f0)
	/go/src/github.com/cweill/gotests/gotests.go:101 +0xb7
github.com/cweill/gotests.parallelize.func1(0xc4200a4420, 0xc42008ca90, 0x1, 0x1, 0xc42008a900, 0xc42008e540, 0x7ffd49b286e2, 0x30)
	/go/src/github.com/cweill/gotests/gotests.go:73 +0xb7
created by github.com/cweill/gotests.parallelize
	/go/src/github.com/cweill/gotests/gotests.go:70 +0x125

	at ChildProcess.exithandler (child_process.js:217:12)
	at emitTwo (events.js:106:13)
	at ChildProcess.emit (events.js:194:7)
	at maybeClose (internal/child_process.js:899:16)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
```

**Comment by cweill** [comment]
I'll mark this as fixed by #50.
