### ISSUE TITLE
Index out of range when generating tests

### ISSUE THREAD

**Issue by spdowling** [cweill/gotests#69]
When attempting to generate tests:

```
gotests -all -i -w .
```

I get the following panic:

```
panic: runtime error: index out of range

goroutine 19 [running]:
go/types.(*object).Name(...)
	/usr/local/Cellar/go/1.9.2/libexec/src/go/types/type.go:146
github.com/cweill/gotests/internal/goparser.parseReceiver(0xc4201979e0, 0xc4201e02d0, 0xc4201e0300, 0x14cdd20)
	/Users/simon/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:231 +0x430
github.com/cweill/gotests/internal/goparser.parseFunc(0xc420197fb0, 0xc4201e02d0, 0xc4201e0300, 0x1)
	/Users/simon/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:178 +0x9d
github.com/cweill/gotests/internal/goparser.(*Parser).parseFunctions(0xc420073ed0, 0xc4201a8840, 0xc4201be600, 0xc4201949a8, 0x1, 0x1, 0x43e9, 0x1, 0x1)
	/Users/simon/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:105 +0x108
github.com/cweill/gotests/internal/goparser.(*Parser).Parse(0xc420073ed0, 0xc4201e80c0, 0x51, 0xc42018e8b0, 0x1, 0x1, 0x10100f7, 0xc4201ac520, 0x20)
	/Users/simon/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:58 +0x2da
github.com/cweill/gotests.generateTest(0xc4201e80c0, 0x51, 0xc42018e8b0, 0x1, 0x1, 0xc42020c300, 0x0, 0xc420029fa0, 0x1111e70)
	/Users/simon/go/src/github.com/cweill/gotests/gotests.go:102 +0xba
github.com/cweill/gotests.parallelize.func1(0xc42019c1e0, 0xc42018e8b0, 0x1, 0x1, 0xc42020c300, 0xc4201f20c0, 0xc4201e80c0, 0x51)
	/Users/simon/go/src/github.com/cweill/gotests/gotests.go:74 +0xb7
created by github.com/cweill/gotests.parallelize
	/Users/simon/go/src/github.com/cweill/gotests/gotests.go:71 +0x125
```

**Comment by arduanov** [comment]
Same error, failed on struct with interface embedding
```
type Context struct {
	handlers.AppIface
}

func (c *Context) Myfync() {

}
```
error
```
panic: runtime error: index out of range

goroutine 7 [running]:
go/types.(*Struct).Field(...)
        /usr/local/Cellar/go/1.10.2/libexec/src/go/types/type.go:146
github.com/cweill/gotests/internal/goparser.parseReceiver(0xc4201cc7b0, 0xc4201cd0b0, 0xc4201cd0e0, 0xc4200253c0)
        /Users/m.arduanov/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:231 +0x3cb
github.com/cweill/gotests/internal/goparser.parseFunc(0xc4201cc870, 0xc4201cd0b0, 0xc4201cd0e0, 0x1)
        /Users/m.arduanov/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:178 +0x9a
github.com/cweill/gotests/internal/goparser.(*Parser).parseFunctions(0xc42005bee0, 0xc420025000, 0xc4200aa580, 0xc42000c228, 0x1,0x1, 0x77b, 0x1, 0x1)
        /Users/m.arduanov/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:105 +0x102
github.com/cweill/gotests/internal/goparser.(*Parser).Parse(0xc42005bee0, 0xc420022240, 0x53, 0xc420064c60, 0x1, 0x1, 0x100f4c9, 0xc42000a920, 0x20)
        /Users/m.arduanov/go/src/github.com/cweill/gotests/internal/goparser/goparser.go:58 +0x2da
github.com/cweill/gotests.generateTest(0xc420022240, 0x53, 0xc420064c60, 0x1, 0x1, 0xc4201cc630, 0x0, 0x110662c, 0xc4201ee380)
        /Users/m.arduanov/go/src/github.com/cweill/gotests/gotests.go:102 +0xb7
github.com/cweill/gotests.parallelize.func1(0xc42001a4e0, 0xc420064c60, 0x1, 0x1, 0xc4201cc630, 0xc420070540, 0xc420022240, 0x53)
        /Users/m.arduanov/go/src/github.com/cweill/gotests/gotests.go:74 +0xb1
created by github.com/cweill/gotests.parallelize
        /Users/m.arduanov/go/src/github.com/cweill/gotests/gotests.go:71 +0x125
```
